version: '3'

services:
  flask_app:
    container_name: flask_app
    image: flask_app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres 
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    container_name: frontend_app
    image: baofci/reactjs
    ports: 
      - "5173:5173"

volumes:
  pgdata: {}
